"""PatchPilot core: domain models, interfaces, configuration and shared utilities.

Every other package depends on this one; this one depends on nothing inside
PatchPilot. That is what keeps the indexer, agent, sandbox and evaluation
harness independently testable.
"""

from __future__ import annotations

from .config import Settings, get_settings, reset_settings
from .enums import (
    TERMINAL_STATUSES,
    CommandKind,
    JobStatus,
    JobType,
    PatchRejectionReason,
    RetrievalReason,
    RunState,
    RunStatus,
    SandboxStatus,
    StopReason,
    SymbolType,
)
from .errors import (
    AuthenticationError,
    ConfigurationError,
    ConflictError,
    IndexingError,
    ModelAdapterError,
    NotFoundError,
    PatchError,
    PatchPilotError,
    PolicyError,
    QueueFullError,
    RepositoryError,
    RetrievalError,
    SandboxError,
    SandboxUnavailableError,
    StructuredOutputError,
    ValidationError,
)
from .models import (
    AttemptRecord,
    ChatMessage,
    CodeChunk,
    CommandResult,
    CommandSpec,
    ContextPackage,
    CostEstimate,
    FileChange,
    FileRecord,
    ImportEdge,
    IndexStats,
    IssueSpec,
    LatencyBreakdown,
    LLMResponse,
    PatchProposal,
    PatchValidationResult,
    RepairPlan,
    RepositorySpec,
    RetrievedChunk,
    RunConfig,
    RunSummary,
    SandboxExecution,
    SandboxLimits,
    ScoreComponent,
    StateTransition,
    SymbolRef,
    TokenUsage,
    utcnow,
)

__all__ = [
    "TERMINAL_STATUSES",
    "AttemptRecord",
    "AuthenticationError",
    "ChatMessage",
    "CodeChunk",
    "CommandKind",
    "CommandResult",
    "CommandSpec",
    "ConfigurationError",
    "ConflictError",
    "ContextPackage",
    "CostEstimate",
    "FileChange",
    "FileRecord",
    "ImportEdge",
    "IndexStats",
    "IndexingError",
    "IssueSpec",
    "JobStatus",
    "JobType",
    "LLMResponse",
    "LatencyBreakdown",
    "ModelAdapterError",
    "NotFoundError",
    "PatchError",
    "PatchPilotError",
    "PatchProposal",
    "PatchRejectionReason",
    "PatchValidationResult",
    "PolicyError",
    "QueueFullError",
    "RepairPlan",
    "RepositoryError",
    "RepositorySpec",
    "RetrievalError",
    "RetrievalReason",
    "RetrievedChunk",
    "RunConfig",
    "RunState",
    "RunStatus",
    "RunSummary",
    "SandboxError",
    "SandboxExecution",
    "SandboxLimits",
    "SandboxStatus",
    "SandboxUnavailableError",
    "ScoreComponent",
    "Settings",
    "StateTransition",
    "StopReason",
    "StructuredOutputError",
    "SymbolRef",
    "SymbolType",
    "TokenUsage",
    "ValidationError",
    "get_settings",
    "reset_settings",
    "utcnow",
]
