"""initial schema

Revision ID: 01aa0f50dff0
Revises:
Create Date: 2026-09-16 18:11:05.601784
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '01aa0f50dff0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('commit_sha', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('local_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index('ix_repositories_url', ['url'], unique=False)

    op.create_table('benchmark_results',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('benchmark_id', sa.String(length=48), nullable=False),
    sa.Column('task_id', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('baseline_failed', sa.Boolean(), nullable=True),
    sa.Column('patch_applied', sa.Boolean(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('sandbox_failed', sa.Boolean(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benchmark_results', schema=None) as batch_op:
        batch_op.create_index('ix_benchmark_results_benchmark', ['benchmark_id', 'model'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('repository_id', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_indexes',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('repository_id', sa.String(length=48), nullable=False),
    sa.Column('repo_sha', sa.String(length=80), nullable=False),
    sa.Column('root_path', sa.String(length=1000), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('conventions', sa.JSON(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('vector_store', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'repo_sha', name='uq_index_repo_sha')
    )
    with op.batch_alter_table('repository_indexes', schema=None) as batch_op:
        batch_op.create_index('ix_repository_indexes_sha', ['repo_sha'], unique=False)

    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.String(length=48), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('repo_sha', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=400), nullable=False),
    sa.Column('symbol_type', sa.String(length=32), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('imports', sa.JSON(), nullable=False),
    sa.Column('calls', sa.JSON(), nullable=False),
    sa.Column('calls_resolved', sa.JSON(), nullable=False),
    sa.Column('called_by', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['repository_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'chunk_id', name='uq_chunk_per_index')
    )
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_code_chunks_index_path', ['index_id', 'path'], unique=False)

    op.create_table('import_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.String(length=48), nullable=False),
    sa.Column('source_path', sa.String(length=600), nullable=False),
    sa.Column('target_path', sa.String(length=600), nullable=True),
    sa.Column('module', sa.String(length=400), nullable=False),
    sa.Column('symbol', sa.String(length=200), nullable=True),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['repository_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_edges', schema=None) as batch_op:
        batch_op.create_index('ix_import_edges_index_source', ['index_id', 'source_path'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('repository_id', sa.String(length=48), nullable=False),
    sa.Column('issue_id', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stop_reason', sa.String(length=48), nullable=True),
    sa.Column('repo_sha', sa.String(length=80), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_known', sa.Boolean(), nullable=False),
    sa.Column('latency', sa.JSON(), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=True),
    sa.Column('baseline_reproduced', sa.Boolean(), nullable=True),
    sa.Column('context_package', sa.JSON(), nullable=True),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=32), nullable=True),
    sa.Column('sandbox_isolated', sa.Boolean(), nullable=False),
    sa.Column('final_patch', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('benchmark_result_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_model', ['model'], unique=False)
        batch_op.create_index('ix_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.String(length=48), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('qualified_name', sa.String(length=400), nullable=False),
    sa.Column('symbol_type', sa.String(length=32), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['repository_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index('ix_symbols_index_path', ['index_id', 'path'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifacts_run', ['run_id', 'attempt'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('plan_error', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('diff_hash', sa.String(length=32), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('execution', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('should_retry', sa.Boolean(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'attempt', name='uq_attempt_per_run')
    )
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'index', name='uq_event_index_per_run')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_run_events_run', ['run_id', 'index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('ix_run_events_run')

    op.drop_table('run_events')
    op.drop_table('attempts')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_run')

    op.drop_table('artifacts')
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index('ix_symbols_index_path')

    op.drop_table('symbols')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status_created')
        batch_op.drop_index('ix_runs_model')

    op.drop_table('runs')
    with op.batch_alter_table('import_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_import_edges_index_source')

    op.drop_table('import_edges')
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_code_chunks_index_path')

    op.drop_table('code_chunks')
    with op.batch_alter_table('repository_indexes', schema=None) as batch_op:
        batch_op.drop_index('ix_repository_indexes_sha')

    op.drop_table('repository_indexes')
    op.drop_table('issues')
    with op.batch_alter_table('benchmark_results', schema=None) as batch_op:
        batch_op.drop_index('ix_benchmark_results_benchmark')

    op.drop_table('benchmark_results')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index('ix_repositories_url')

    op.drop_table('repositories')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created')

    op.drop_table('jobs')
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
